all = { import* ~ other }

WHITESPACE = _{ (" " | "\r\n" | "\n" | "\t")+ }

COMMENT = _{
    "//" ~ (!("\n"|"\r\n") ~ ANY)
  | "/*" ~ (!"*/" ~ ANY)
}

identifier = @{
    !reserved_keywords ~ (LETTER | "_") ~ (LETTER | ASCII_DIGIT | "_")*
  | reserved_keywords ~ (LETTER | ASCII_DIGIT | "_")+
}

other = { ANY* }

reserved_keywords = {
    "import"
  | "if"
  | "for"
  | "break"
  | "func"
  | "struct"
  | "size_of"
  | "ret"
  | "cti"
  | "brk"
}
import            = { "import" ~ identifier }
